const HTTP_OK_STATUS = 200;
const HTTP_POSTOK_STATUS = 201;
const HTTP_BADREQUEST_STATUS = 400;
const HTTP_UNAUTHENTICATED_STATUS = 401;
const HTTP_NOTFOUND_STATUS = 404;

module.exports = {
  HTTP_OK_STATUS,
  HTTP_POSTOK_STATUS,
  HTTP_BADREQUEST_STATUS,
  HTTP_UNAUTHENTICATED_STATUS,
  HTTP_NOTFOUND_STATUS,
};
